// import {insiraseuvetoraqui} from './dados.js'
// <script type="module" src="scriptprincipal.js"></script>     // Declare dessa forma

export var tohpicos = [     // SUBTÓPICO    TÓPICO      COR
    ['Ciência, tecnologia e sociedade', 'Iniciação à Física', '#c94277'],
    ['Ramos da Física', 'Iniciação à Física', '#c94277'],
    ['Notação científica', 'Iniciação à Física', '#c94277'],
    ['Ordens de Grandeza', 'Iniciação à Física', '#c94277'],
    ['Grandezas e Unidades', 'Iniciação à Física', '#c94277'],
    ['Sistema Internacional de Unidades', 'Iniciação à Física', '#c94277'],
    ['Algarismos significativos', 'Iniciação à Física', '#c94277'],

    ['Vetores ', 'Dinâmica', '#f06543'],
    ['Leis de Newton ', 'Dinâmica', '#f06543'],
    ['Aplicações das Leis de Newton', 'Dinâmica', '#f06543'],

    ['Noções de movimento', 'Cinemática', '#eac435'],
    ['Movimento Uniforme e Uniformemente Variado', 'Cinemática', '#eac435'],
    ['Movimento Circular Uniforme e Forças em trajetórias curvilíneas ', 'Cinemática', '#eac435'],

    ['Histórico', 'Gravitação Universal', '#5fad56'],
    ['Leis de Kepler', 'Gravitação Universal', '#5fad56'],
    ['Lei da gravitação universal', 'Gravitação Universal', '#5fad56'],
    ['Movimento de satélites', 'Gravitação Universal', '#5fad56'],

    ['Momento de uma força (Torque)', 'Estática', '#586994'],
    ['Equilíbrio de um ponto material', 'Estática', '#586994'],
    ['Equilíbrio de um corpo rígido', 'Estática', '#586994'],
    ['Alavancas', 'Estática', '#586994'],

    ['Trabalho e Potência', 'Leis de Conservação', '#7a3b69'],
    ['Energia Mecânica', 'Leis de Conservação', '#7a3b69'],
    ['Conservação de energia', 'Leis de Conservação', '#7a3b69'],
    ['Impulso e quantidade de movimento', 'Leis de Conservação', '#7a3b69'],
    ['Forças impulsivas e colisões', 'Leis de Conservação', '#7a3b69'],
    ['Conservação da quantidade de movimento', 'Leis de Conservação', '#7a3b69'],

    ['Física Geral', '', '#c94277'],
    ['Dinâmica', '', '#f06543'],
    ['Cinemática', '', '#eac435'],
    ['Gravitação Universal', '', '#5fad56'],
    ['Estática', '', '#586994'],
    ['Leis de Conservação', '', '#7a3b69']
]

//  < + >  < + >  < + >  < + >  < + >  < + >  < + >
//   >  < + >  < + >  < + >  < + >  < + >  < + >
//  < + >  < + >  < + >  < + >  < + >  < + >  < + >

export var canais = [     // NOME    ORIGEM      IMAGEM      ENDEREÇO
    ['MathGurl', 'YouTube', 'mathgurl.jpg', 'https://www.youtube.com/c/MathGurl'],
    ['Isto é Matemática', 'YouTube', 'isto-eh-matemahtica.jpg', 'https://www.youtube.com/c/istoematematica'],
    ['Manual do Mundo', 'YouTube', 'manual-do-mundo.jpg', 'https://www.youtube.com/c/manualdomundo'],
    ['Chama o Físico', 'YouTube', 'chama-o-fihsico.jpg', 'https://www.youtube.com/c/ChamaoF%C3%ADsico'],
    ['Ciência Todo Dia', 'YouTube', 'ciencia-todo-dia.jpg', 'https://www.youtube.com/c/CienciaTodoDia'],
    ['Physics Girl', 'YouTube', 'physics-girl.jpg', 'https://www.youtube.com/c/physicsgirl'],
    ['Veritasium', 'YouTube', 'veritasium.jpg', 'https://www.youtube.com/c/veritasium'],
    ['Minuto da Física', 'YouTube', 'minuto-da-fihsica.jpg', 'https://www.youtube.com/c/MinutoDaFisica'],
    ['Universo Narrado', 'YouTube', 'universo-narrado.jpg', 'https://www.youtube.com/c/UniversoNarrado'],
    ['Pura Física', 'YouTube', 'pura-fihsica.jpg', 'https://www.youtube.com/c/PuraF%C3%ADsica'],
    ['Canal Nostalgia', 'YouTube', 'canal-nostalgia.jpg', 'https://www.youtube.com/nostalgia'],
    ['Kurzgesagt – In a Nutshell', 'YouTube', 'kurzgesagt-in-a-nutshell.jpg', 'https://www.youtube.com/c/inanutshell'],
    ['Nerdologia', 'YouTube', 'nerdologia.jpg', 'https://www.youtube.com/c/nerdologia'],
    ['Ponto em Comum', 'YouTube', 'ponto-em-comum.jpg', 'https://www.youtube.com/c/PontoemComumcomMigueleosHugobertos'],
    ['CuriosaMente', 'YouTube', 'curiosamente.jpg', 'https://www.youtube.com/c/curiosamente'],
    ['Ter', 'YouTube', 'ter.jpg', 'https://www.youtube.com/c/Tercosmicqueen'],
    ['ameninadamatematica', 'TikTok', 'ameninadamatematica.jpeg', 'https://www.tiktok.com/@ameninadamatematica'],
    ['afrofisico', 'TikTok', 'afrofisico.jpeg', 'https://www.tiktok.com/@afrofisico'],
    ['prof_bressan', 'TikTok', 'prof_bressan.jpeg', 'https://www.tiktok.com/@prof_bressan'],
    ['oprof.leo', 'TikTok', 'oprof.leo.jpeg', 'https://www.tiktok.com/@oprof.leo'],
    ['professorodnil', 'TikTok', 'professorodnil.jpeg', 'https://www.tiktok.com/@professorodnil'],
    ['fisicanofusca', 'TikTok', 'fisicanofusca.jpg', 'https://www.tiktok.com/@fisicanofusca'],
    ['professorbraian', 'TikTok', 'professorbraian.jpeg', 'https://www.tiktok.com/@professorbraian'],
    ['partiufisica', 'TikTok', 'partiufisica.jpeg', 'https://www.tiktok.com/@partiufisica'],
    ['purafisica', 'TikTok', 'pura-fihsica.jpg', 'https://www.tiktok.com/@purafisica'],
    ['manualdomundo', 'TikTok', 'manual-do-mundo.jpg', 'https://www.tiktok.com/@manualdomundo'],
    ['thephysicsgirl', 'TikTok', 'thephysicsgirl.jpeg', 'https://www.tiktok.com/@thephysicsgirl'],
    ['estudematematica', 'TikTok', 'estudematematica.jpeg', 'https://www.tiktok.com/@estudematematica'],
    ['opedroloos', 'TikTok', 'opedroloos.jpeg', 'https://www.tiktok.com/@opedroloos'],
    ['Cana Aletório', 'YouTube', '', '']
]

//  < + >  < + >  < + >  < + >  < + >  < + >  < + >
//   >  < + >  < + >  < + >  < + >  < + >  < + >
//  < + >  < + >  < + >  < + >  < + >  < + >  < + >

export var postes = [     //    ºTÓPICO     ºCANAL    DESCRIÇÃO     IFRAME-DO-VÍDEO (NOME-DO-VÍDEO/LINK-DO-VÍDEO)

    [2, 3 , 'movimento circular rampa circular', 'cpy4V2Bk0jc?start=0&end=58'],
    [26, 3 , 'conservação de momento', 'xSAnySixRjA?start=0&end=39'],
    [10, 3 , 'ZERO-G girl', 'q1_AJWZajEk?start=127&end=275'],
    [10, 3 , 'ZERO-G', 'xdJwG_9kF8s?start=0&end=48'],
    [10, 3 , 'cancelar a gravidade', '2i0GsErWF50?start=40&end=80'],
    [0, 3 , 'filme gravidade', 'CcM4eEE4R0Q?start=18&end=112'],
    [17, 3 , 'notre dame', 'bloOQd5YUQg?start=0&end=150'],
    [22, 3 , '(Espanhol) energia', 'KlRLGXbtgAA?start=0&end=192'],
    [0, 3 , 'Lua vs celular', 'AOFqgD4Ay6A?start=0&end=104'],
    [0, 3 , 'Eclipse em sobral', 'u9pBT5i3h6A?start=0&end=54'],
    [16, 3 , 'Se a lua caisse na terra', 'lheapd7bgLA?start=24&end=84'],
    [13, 3 , 'terra plana', 'nEVPDqUb5dM?start=150&end=314'],
    [0, 3 , 'Mulheres na ciência', 'WWvIQJg4SCM?start=304&end=365'],
    [22, 3 , 'energia e trabalho', 'szh4xAlwjh8?start=102&end=232'],
    [0, 3 , 'O que precisa para se dar bem na física', 'URPGASbHUIo?start=39&end=101'],
    [8, 3 , 'Mola que cai', 'jtteNHcEvFk?playlist=jtteNHcEvFk&loop=1'],
    [22, 3 , 'Skate', 'b6NinDVNFc8?playlist=b6NinDVNFc8&loop=1'],
    [23, 3 , 'Conservação de energia pendulo peão', '993ZAPEr6QY?playlist=993ZAPEr6QY&loop=1'],
    [10, 3 , 'Velocidade de reação do golero', 'yKw9E3CQyOE?playlist=yKw9E3CQyOE&loop=1'],
    [10, 3 , 'Bola no carro', 'ayPY-bCFad4?playlist=ayPY-bCFad4&loop=1'],
    [25, 3 , 'Caixa que cai e volta', 'T6kXO-Tt5jU?playlist=T6kXO-Tt5jU&loop=1'],
    [25, 3 , 'Fisica do futebol', 'Isy99ARz2to?start=15&end=88'],
    [25, 3 , 'tenis de mesa', 'GVq9m0epMFw?start=180&end=327'],
    [15, 3 , 'ibere em queda livre', 'y6gNCTke7xg?start=52&end=225'],
    [9, 3 , 'inercia no parque da disney', 'eUPiaaNlPas?start=43&end=253'],
    [0, 3 , 'homem aranha', 'EIdDwLhcU_k?start=17&end=75'],
    [0, 3 , 'Cosmo comentário', 'Dk62VP-8VEE?start=37&end=75'],
    [0, 3 , 'Interstelar', 'mbbPSq63yuM?playlist=mbbPSq63yuM&loop=1'],
    [0, 3 , 'Fisica intra estelar', 'hvj_E767qyo?start=20&end=82'],
    [0, 3 , 'Filmes: Radioctivity', 'rIw9djmyPog&t=38s?playlist=rIw9djmyPog&t=38s&loop=1'],
    [0, 3 , 'Filme passageiro', 'TyUa0rG9Mn0?playlist=TyUa0rG9Mn0&loop=1'],
    [0, 3 , 'Filme perdido em marte', 'tCAgtzMUCaA?playlist=tCAgtzMUCaA&loop=1'],
    [0, 3 , 'nerdologia perdido em marte', 'JZXHZitYSqE?start=25&end=85'],
    [0, 3 , 'Filme estrela além do tempo', 'JudEsE3sPSg?playlist=JudEsE3sPSg&loop=1'],
    [1, 3 , '(Em inglês) mapa da física', 'ZihywtixUYo?start=24&end=215'],
    [1, 3 , 'mapa da física', 'juilCMQvARs?start=42&end=263'],
    [2, 3 , 'potências', 'iHYBZIDM1lw?start=62&end=216'],
    [3, 3 , 'prefixo do SI', 'cDKQre30RS8?start=55&end=115'],
    [4, 3 , 'grandezas fisicas', 'LZPiq8RK9j0?start=0&end=53'],
    [4, 3 , 'mais medidas', 'lEyUFyKPqXA?start=38&end=230'],
    [5, 3 , 'unidades de medidas', 'rv2gRtVcHG4?start=0&end=71'],
    [5, 3 , 'medidas', 'MeEGw_O7c8E?start=17&end=184'],
    [7, 3 , 'vetor brasil escola', 'lexlX6PurIU?start=77&end=157'],
    [8, 3 , 'movimento', 'B2u8FYE9fWk?start=0&end=77'],
    [9, 3 , 'cama elastica em movimento', 'rwqlRjpsa3I?playlist=rwqlRjpsa3I&loop=1'],
    [9, 3 , 'queda de braço', 'KWxoYejamZ8?playlist=KWxoYejamZ8&loop=1'],
    [9, 3 , 'cães conhecem as leis de newton', 'mYoK4a7Dut8?playlist=mYoK4a7Dut8&loop=1'],
    [12, 3 , 'Chute composição de movimento', 'C7YN_xTlLLs?playlist=C7YN_xTlLLs&loop=1'],
    [12, 3 , 'saindo do buraco', 'jHhjDGiUKME?playlist=jHhjDGiUKME&loop=1'],
    [12, 3 , 'girando escova no dedo', 'wl3Ubp8Opbw?start=28&end=77'],
    [12, 3 , 'ensinando a girar caderno na mão', 'TcqWbzTcRLk?playlist=TcqWbzTcRLk&loop=1'],
    [12, 3 , 'catchoro fazendo MCU', 'JYDa35xTl4s?playlist=JYDa35xTl4s&loop=1'],
    [13, 3 , 'cosmos nicolau', 'tyCK9jVf_-4?end=97'],
    [13, 3 , 'socrática primeira lei de kepler', 'g1b8zZ3LZhY?end=90'],
    [14, 3 , 'modelo helio centrico', '1dBYixqIoYU?start=141&end=197'],
    [13, 3 , 'leis de kepleer', '6jXN_1Xt20M?start=179&end=413'],
    [15, 3 , 'lançamento', 'YbDSfRLF23I?start=2199&end=2265'],
    [16, 3 , 'ISS no BR', 'kPADmYSHETo?start=870&end=930'],
    [16, 3 , 'Gravidade no sistema solar', 'ZmFvwb0LtJk?&playlist=ZmFvwb0LtJk&loop=1'],
    [16, 3 , 'sputinique', 'jSIImWfwn94?playlist=jSIImWfwn94&loop=1'],
    [16, 3 , 'sputinique', 'ZtwgqpUibfU?start=56&end=66'],  
    [19, 3 , 'banco em equilibrio', 'ZZnw_qyvP68?playlist=ZZnw_qyvP68&loop=1'],
    [24, 3 , 'momento linear', 'Seb29XUjakk?start=138&end=195'],
    [23, 3 , 'energia cinética e potencial', '4I3eoUffsEc?start=75&end=175'],
    [23, 3 , 'pendulo no rosto', 'onxGV17isfQ?start=138&end=147'],
    [17, 3 , 'torque na porta', 'YoXpG9lw_lc?start=163&end=174'],
    [20, 3 , 'alavancas', '5u5klXLCOtU?start=502']
]
