// import {insiraseuvetoraqui} from './dados.js'
// <script type="module" src="scriptprincipal.js"></script>     // Declare dessa forma

export var tohpicos = [     // SUBTÓPICO    TÓPICO      COR
    ['Ciência, tecnologia e sociedade', 'Iniciação à Física', '#c94277'],
    ['Ramos da Física', 'Iniciação à Física', '#c94277'],
    ['Notação científica', 'Iniciação à Física', '#c94277'],
    ['Ordens de Grandeza', 'Iniciação à Física', '#c94277'],
    ['Grandezas e Unidades', 'Iniciação à Física', '#c94277'],
    ['Sistema Internacional de Unidades', 'Iniciação à Física', '#c94277'],
    ['Algarismos significativos', 'Iniciação à Física', '#c94277'],

    ['Vetores ', 'Dinâmica', '#f06543'],
    ['Leis de Newton ', 'Dinâmica', '#f06543'],
    ['Aplicações das Leis de Newton', 'Dinâmica', '#f06543'],

    ['Noções de movimento', 'Cinemática', '#eac435'],
    ['Movimento Uniforme e Uniformemente Variado', 'Cinemática', '#eac435'],
    ['Movimento Circular Uniforme e Forças em trajetórias curvilíneas ', 'Cinemática', '#eac435'],

    ['Histórico', 'Gravitação Universal', '#5fad56'],
    ['Leis de Kepler', 'Gravitação Universal', '#5fad56'],
    ['Lei da gravitação universal', 'Gravitação Universal', '#5fad56'],
    ['Movimento de satélites', 'Gravitação Universal', '#5fad56'],

    ['Momento de uma força (Torque)', 'Estática', '#586994'],
    ['Equilíbrio de um ponto material', 'Estática', '#586994'],
    ['Equilíbrio de um corpo rígido', 'Estática', '#586994'],
    ['Alavancas', 'Estática', '#586994'],

    ['Trabalho e Potência', 'Leis de Conservação', '#7a3b69'],
    ['Energia Mecânica', 'Leis de Conservação', '#7a3b69'],
    ['Conservação de energia', 'Leis de Conservação', '#7a3b69'],
    ['Impulso e quantidade de movimento', 'Leis de Conservação', '#7a3b69'],
    ['Forças impulsivas e colisões', 'Leis de Conservação', '#7a3b69'],
    ['Conservação da quantidade de movimento', 'Leis de Conservação', '#7a3b69'],

    ['Física Geral', '', '#c94277'],
    ['Dinâmica', '', '#f06543'],
    ['Cinemática', '', '#eac435'],
    ['Gravitação Universal', '', '#5fad56'],
    ['Estática', '', '#586994'],
    ['Leis de Conservação', '', '#7a3b69']
]

//  < + >  < + >  < + >  < + >  < + >  < + >  < + >
//   >  < + >  < + >  < + >  < + >  < + >  < + >
//  < + >  < + >  < + >  < + >  < + >  < + >  < + >

export var canais = [     // NOME    ORIGEM      IMAGEM      ENDEREÇO
    ['MathGurl', 'YouTube', 'mathgurl.jpg', 'https://www.youtube.com/c/MathGurl'],
    ['Isto é Matemática', 'YouTube', 'isto-eh-matemahtica.jpg', 'https://www.youtube.com/c/istoematematica'],
    ['Manual do Mundo', 'YouTube', 'manual-do-mundo.jpg', 'https://www.youtube.com/c/manualdomundo'],
    ['Chama o Físico', 'YouTube', 'chama-o-fihsico.jpg', 'https://www.youtube.com/c/ChamaoF%C3%ADsico'],
    ['Ciência Todo Dia', 'YouTube', 'ciencia-todo-dia.jpg', 'https://www.youtube.com/c/CienciaTodoDia'],
    ['Physics Girl', 'YouTube', 'physics-girl.jpg', 'https://www.youtube.com/c/physicsgirl'],
    ['Veritasium', 'YouTube', 'veritasium.jpg', 'https://www.youtube.com/c/veritasium'],
    ['Minuto da Física', 'YouTube', 'minuto-da-fihsica.jpg', 'https://www.youtube.com/c/MinutoDaFisica'],
    ['Universo Narrado', 'YouTube', 'universo-narrado.jpg', 'https://www.youtube.com/c/UniversoNarrado'],
    ['Pura Física', 'YouTube', 'pura-fihsica.jpg', 'https://www.youtube.com/c/PuraF%C3%ADsica'],
    ['Canal Nostalgia', 'YouTube', 'canal-nostalgia.jpg', 'https://www.youtube.com/nostalgia'],
    ['Kurzgesagt – In a Nutshell', 'YouTube', 'kurzgesagt-in-a-nutshell.jpg', 'https://www.youtube.com/c/inanutshell'],
    ['Nerdologia', 'YouTube', 'nerdologia.jpg', 'https://www.youtube.com/c/nerdologia'],
    ['Ponto em Comum', 'YouTube', 'ponto-em-comum.jpg', 'https://www.youtube.com/c/PontoemComumcomMigueleosHugobertos'],
    ['CuriosaMente', 'YouTube', 'curiosamente.jpg', 'https://www.youtube.com/c/curiosamente'],
    ['Ter', 'YouTube', 'ter.jpg', 'https://www.youtube.com/c/Tercosmicqueen'],
    ['ameninadamatematica', 'TikTok', 'ameninadamatematica.jpeg', 'https://www.tiktok.com/@ameninadamatematica'],
    ['afrofisico', 'TikTok', 'afrofisico.jpeg', 'https://www.tiktok.com/@afrofisico'],
    ['prof_bressan', 'TikTok', 'prof_bressan.jpeg', 'https://www.tiktok.com/@prof_bressan'],
    ['oprof.leo', 'TikTok', 'oprof.leo.jpeg', 'https://www.tiktok.com/@oprof.leo'],
    ['professorodnil', 'TikTok', 'professorodnil.jpeg', 'https://www.tiktok.com/@professorodnil'],
    ['fisicanofusca', 'TikTok', 'fisicanofusca.jpg', 'https://www.tiktok.com/@fisicanofusca'],
    ['professorbraian', 'TikTok', 'professorbraian.jpeg', 'https://www.tiktok.com/@professorbraian'],
    ['partiufisica', 'TikTok', 'partiufisica.jpeg', 'https://www.tiktok.com/@partiufisica'],
    ['purafisica', 'TikTok', 'pura-fihsica.jpg', 'https://www.tiktok.com/@purafisica'],
    ['manualdomundo', 'TikTok', 'manual-do-mundo.jpg', 'https://www.tiktok.com/@manualdomundo'],
    ['thephysicsgirl', 'TikTok', 'thephysicsgirl.jpeg', 'https://www.tiktok.com/@thephysicsgirl'],
    ['estudematematica', 'TikTok', 'estudematematica.jpeg', 'https://www.tiktok.com/@estudematematica'],
    ['opedroloos', 'TikTok', 'opedroloos.jpeg', 'https://www.tiktok.com/@opedroloos'],
    ['Canal Avulso', 'YouTube', 'canal-avulso.png', '0'],
    ['QuantumFracture', 'YouTube', 'quantumfracture.jpg', 'https://www.youtube.com/channel/UCbdSYaPD-lr1kW27UJuk8Pw'],
    ['Socratica ', 'YouTube', 'socratica.jpg', 'https://www.youtube.com/user/SocraticaPortugues/videos'],
    ['Teoria de Tudo', 'YouTube', 'teoria-de-tudo.jpg', 'https://www.youtube.com/c/TeoriadeTudo1/videos'],
    ['A Física', 'YouTube', 'a-fihsica.jpg', 'https://www.youtube.com/channel/UCn7g7UYG8rD-XwMnqNjG4XA']
]

//  < + >  < + >  < + >  < + >  < + >  < + >  < + >
//   >  < + >  < + >  < + >  < + >  < + >  < + >
//  < + >  < + >  < + >  < + >  < + >  < + >  < + >

export var postes = [     //    ºTÓPICO     ºCANAL    DESCRIÇÃO     IFRAME-DO-VÍDEO (NOME-DO-VÍDEO/LINK-DO-VÍDEO)
    [27, 33, 'Dicas, servem tanto para quem quer fazer carreira, quanto para quem não quer fazer da física uma preocupação no Ensino Médio.', 'URPGASbHUIo?start=39&end=101'],
    [27, 12, 'Comparação de grandezas entre o homem aranha e as aranhas.', 'EIdDwLhcU_k?start=17&end=75'],
    [27, 29, 'Um dos melhores filmes de ficção científica, vale muito a pena. Tá lá no HBO max.', 'mbbPSq63yuM?playlist=mbbPSq63yuM&loop=1'],
    [27, 12, 'Se você já assistiu Interestelar veja parte da física por trás do filme.', 'hvj_E767qyo?start=20&end=82'],
    [28, 28, 'Com vocês o conceito mais importante para esse ano MOVIMENTO.', 'B2u8FYE9fWk?start=0&end=77'],
    [28, 25, 'Sentindo a inércia no próprio corpo, no parque da disney.', 'eUPiaaNlPas?start=43&end=253'],
    [28, 24, 'Seu doguinho manja tudo de física, não vá perder para ele.', 'mYoK4a7Dut8?playlist=mYoK4a7Dut8&loop=1'],
    [28, 3, 'Vetores são tudo em física, quase isso, vale muito aprender usá-los.', 'GB-ai7x1wJk?start=38&end=126'],
    [28, 21, 'Conceito de força na prática, veja para que sentido aponta a força resultante.', 'KWxoYejamZ8?playlist=KWxoYejamZ8&loop=1'],
    [28, 21, 'Olha só como o movimento pode parecer diferente se visto de lugares diferentes.', 'ayPY-bCFad4?playlist=ayPY-bCFad4&loop=1'],
    [28, 18, 'Gente, e essa mola, tá certo isso? Quem sabe física sabe.', 'jtteNHcEvFk?playlist=jtteNHcEvFk&loop=1'],
    [27, 29, 'Uma das mentes mais geniais da humanidade, ela era mulher e mudou a história da física. Filmaço, tá na Netflix.', 'rIw9djmyPog&t=38s?playlist=rIw9djmyPog&t=38s&loop=1'],
    [27, 12, 'A física é para todas e todos, embora o nome de muitas mulheres não seja lembrado, elas sempre produziram conhecimento.', 'WWvIQJg4SCM?start=304&end=365'],
    [27, 29, 'No fim do Ensino Médio vocês vão dominar tudo de física clássica.', 'juilCMQvARs?start=42&end=263'],
    [27, 30, '(Em espanhol) Medir as coisas com precisão é fundamental na física, mas como a gente sabe que está medindo direito?', 'rv2gRtVcHG4?start=0&end=71'],
    [27, 12, 'E como definimos as medidas?', 'MeEGw_O7c8E?start=17&end=184'],
    [29, 29, 'O catchoro mostrando o que é movimento circular.', 'JYDa35xTl4s?playlist=JYDa35xTl4s&loop=1'],
    [29, 29, 'Coisa de físico que domina o MCU (não é o universo da marvel).', 'wl3Ubp8Opbw?start=28&end=77'],
    [29, 29, 'Quem domina a física nunca fica preso.', 'jHhjDGiUKME?playlist=jHhjDGiUKME&loop=1'],
    [29, 26, '(Em inglês) Com conhecimento sempre dá para ser mais radical.', 'cpy4V2Bk0jc?start=0&end=58'],
    [29, 29, 'Um pouquinho de física e você já mandará aquele chute.', 'C7YN_xTlLLs?playlist=C7YN_xTlLLs&loop=1'],
    [29, 25, 'Já para pensar porque as coisas caem?!', 'y6gNCTke7xg?start=52&end=127'],
    [29, 26, '(Em inglês) Que bom seria desligar a gravidade de vez em quando, né?!', 'q1_AJWZajEk?start=127&end=275'],
    [29, 6, '(Em inglês) O mais legal é experimentar como as coisas se comportam sem gravidade.', 'xdJwG_9kF8s?start=216&end=348'],
    [29, 12, 'Como seria cancelar a gravidade.', '2i0GsErWF50?start=40&end=80'],
    [27, 29, 'Cosmos é uma série muito massa, mesmo! Tem duas temporadas e dá para maratonar rapidinho. Tá lá no Disney+.', 'Dk62VP-8VEE?start=37&end=75'],
    [27, 29, 'Passageiros é um filme legal, mas é mais ficção do que ciência. Entretanto essa cena, quando a gravidade da nave é desligada, é muito top.', 'TyUa0rG9Mn0?playlist=TyUa0rG9Mn0&loop=1'],
    [27, 27, 'Matemática é muito importante para física, eu sei que nem todo mundo manda bem na matemática, então é sempre bom estudar um pouquinho.', 'iHYBZIDM1lw?start=62&end=216'],
    [27, 0, '(Em Português) A matemática está em tudo, então não tem muito como fugir.', 'hx-iZrBSkZ0?start=0&end=144'],
    [30, 10, 'Dominar ciência é importante para não cair em pegadinhas, como a terra plana.', 'nEVPDqUb5dM?start=150&end=314'],
    [30, 29, 'Já existiu um tempo que achávamos que a terra era o centro do universo.', 'tyCK9jVf_-4?end=98'],
    [30, 29, 'Fazer ciência é aprender o conhecido e descobrir o novo.', '1dBYixqIoYU?start=132&end=197'],
    [30, 31, 'Para gerar um novo conhecimento é necessário muitas cabeças.', 'g1b8zZ3LZhY?end=90'],
    [30, 29, 'Como nosso conhecimento podemos ver mais longe entender o que era incompreensível.', '6jXN_1Xt20M?start=186&end=413'],
    [30, 29, 'Situação do dia a dia, um bloco de madeiras caindo em um carro, veja como seria se tivessemos outra gravidade.', 'ZmFvwb0LtJk?&playlist=ZmFvwb0LtJk&loop=1'],
    [30, 11, '(Em inglês) E se a lua caísse na terra, a ideia vem do filme "Moon Fall", mas não vou recomendar porque eu ainda não assisti.', 'lheapd7bgLA?start=24&end=84'],
    [30, 25, 'Não faz nem um século que conseguimos a façanha de pôr algo em órbita da terra.', 'jSIImWfwn94?playlist=jSIImWfwn94&loop=1'],
    [30, 29, 'Pessoas, esse som, sei lá, mexe com qualquer um.', 'ZtwgqpUibfU?start=56&end=66'],
    [30, 29, 'Sobre aquelas pessoas que ficam orbitando a terra.', 'K9ScmJa0XSo?start=816&end=940'],
    [30, 8, 'Como faz para colocar algo em órbita.', 'YbDSfRLF23I?start=2199&end=2265'],
    [27, 29, 'O filme está no Disney+, mostra o quão importante três mulheres negras foram para o programa espacial estadunidense.', 'JudEsE3sPSg?playlist=JudEsE3sPSg&loop=1'],
    [27, 29, 'Esse filme é para ficar tenso do começo ao fim, tá lá no HBO max.', '46FXVu9foqo?playlist=46FXVu9foqo&loop=1'],
    [27, 13, 'A tecnologia se aprimora muito rápido, veja o quão sofisticada era a máquina que levou o homem à lua.', 'AOFqgD4Ay6A?start=0&end=104'],
    [31, 18, 'Essas engenhocas me bugam, ainda bem que tem a física para entender.', 'ZZnw_qyvP68?playlist=ZZnw_qyvP68&loop=1'],
    [31, 15, '(Em espanhol) Arquitetura, como conseguimos construir coisas tão altas e finas? você já sabe né?!', 'bloOQd5YUQg?start=0&end=150'],
    [31, 29, 'Essa experiência mega complexa você consegue reproduzir em casa.', '0T2PYYizdgk?playlist=0T2PYYizdgk&loop=1'],
    [27, 29, 'Perdido em Marte, bom filme, você acha no star plus.', 'tCAgtzMUCaA?playlist=tCAgtzMUCaA&loop=1'],
    [27, 12, 'A ciência por trás do filme.', 'JZXHZitYSqE?start=25&end=85'],
    [27, 13, 'Descubra o que Albert Einstein veio fazer em Sobral.', 'u9pBT5i3h6A?start=0&end=54'],
    [32, 20, 'Quando você confia no que estudou.', '993ZAPEr6QY?playlist=993ZAPEr6QY&loop=1'],
    [32, 29, 'Bom, aqui você tem que ir bem além da confiança.', 'onxGV17isfQ?start=494&end=507'],
    [32, 33, 'Energia física tem sua própria definição.', 'szh4xAlwjh8?start=102&end=148'],
    [32, 30, '(Em espanhol) Uma ideia do que é energia, um pouco mais palpável.', 'KlRLGXbtgAA?start=0&end=192'],
    [32, 32, 'Dois tipos de energia que lá para o fim do ano vocês verão.', '4I3eoUffsEc?start=75&end=175'],
    [32, 28, 'Momento também tem seu significado na física.', 'Seb29XUjakk?start=138&end=195'],
    [32, 26, 'Esse brinquedinho é da hora.', 'xSAnySixRjA?start=0&end=39'],
    [32, 21, 'No fim desse eu espero que vocês consigam responder.', 'T6kXO-Tt5jU?playlist=T6kXO-Tt5jU&loop=1'],
    [32, 29, 'As colisões no tênis de mesa.', 'GVq9m0epMFw?start=180&end=327'],
    [32, 12, 'E quanto a física no futebol.', 'Isy99ARz2to?start=15&end=88']
]
